puts true == (true && true)
puts false == (false && true)
puts false == (1 == 1 && 2 == 1)
puts true == ("test" == "test")
puts true == (1 == 1 || 2 != 1)
puts true == (true && 1 == 1)
puts false == (false && 0 != 0)
puts true == (true || 1 == 1)
puts false == ("test" == "testing")
puts false == (1 != 0 && 2 == 1)
puts true == ("test" != "testing")
puts false == ("test" == 1)
puts true == (!(true && false))
puts false == (!(1 == 1 && 0 != 1))
puts false == (!(10 == 1 || 1000 == 1000))
puts false == (!(1 != 10 || 3 == 4))
puts true == (!("testing" == "testing" && "Zed" == "Cool Guy"))
puts true == (1 == 1 && (!("testing" == 1 || 1 == 0)))
puts false == ("chunky" == "bacon" && (!(3 == 4 || 3 == 3)))
puts false == (3 == 3 && (!("testing" == "testing" || "Ruby" == "Fun")))
